### ISSUE TITLE
CrowdFlower KeyError

### ISSUE THREAD

**Issue by LukasS91** [sarnthil/unify-emotion-datasets#21]
Hi guys,

When following the instructions and generating the unified dataset the script throws a KeyError for 'sentiment' in CrowdFlower.

**Comment by L3viathan** [comment]
CrowdFlower became FigureEight, which became Appen. It appears at some point along the way the URL https://www.crowdflower.com/wp-content/uploads/2016/07/text_emotion.csv broke.

It looks like the dataset can still be found here: https://data.world/crowdflower/sentiment-analysis-in-text

**Comment by LukasS91** [comment]
I see, thanks for the fast reply!
